TRUSTED_DOMAINS = ",".join([
    "reuters.com",
    "apnews.com",
    "bloomberg.com",
    "ft.com",
    "wsj.com",
    "economist.com",
    "cnbc.com",
    "fortune.com",
    "forbes.com",
    "businessinsider.com",
    "nytimes.com",
    "theguardian.com",
    "washingtonpost.com",
    "bbc.co.uk",
    "theatlantic.com",
    "techcrunch.com",
    "theverge.com",
    "wired.com",
    "arstechnica.com",
    "venturebeat.com",
    "thenextweb.com",
    "zdnet.com",
    "technologyreview.com",
    "infoworld.com",
    "computerworld.com",
    "sdtimes.com",
    "infoq.com",
    "stackoverflow.blog",
    "github.blog",
])

ROLE_ANCHORS = {
    "individual": [
        '"software engineer"',
        '"software developer"',
        '"frontend developer"',
        '"backend developer"',
        '"full-stack developer"',
        '"junior developer"',
        '"junior engineer"',
        '"entry-level developer"',
        '"senior engineer"',
        '"software programmer"',
    ],
    "collective": [
        '"engineering team"',
        '"developer workforce"',
        '"tech workforce"',
        '"engineering headcount"',
        '"software workforce"',
        '"development team"',
    ]
}

SIGNAL_TOPICS = {
    "workforce_reduction": {
        "phrases": [
            '"engineering layoffs"',
            '"developer layoffs"',
            '"tech layoffs"',
            '"headcount reduction"',
            '"workforce reduction"',
            '"reduction in force"',
            '"job cuts" "engineers"',
            '"let go" "engineers"',
            '"position eliminated" "software"',
        ],
        "role_anchor_group": "collective",
    },
    "ai_displacement": {
        "phrases": [
            '"replace software engineers"',
            '"replace developers"',
            '"replacing programmers"',
            '"AI replaces coders"',
            '"fewer engineers" "AI"',
            '"fewer developers" "AI"',
            '"no longer need developers"',
            '"code without engineers"',
            '"vibe coding"',
            '"one engineer" "AI"',
            '"software without developers"',
        ],
        "role_anchor_group": "individual",
    },
    "hiring_contraction": {
        "phrases": [
            '"hiring freeze" "engineers"',
            '"pause hiring" "developers"',
            '"not hiring" "software"',
            '"cut engineering hiring"',
            '"fewer engineering jobs"',
            '"shrinking engineering"',
        ],
        "role_anchor_group": "individual",
    },
    "junior_displacement": {
        "phrases": [
            '"junior developer" "AI"',
            '"junior engineer" "AI"',
            '"entry-level" "software" "AI"',
            '"coding bootcamp" "jobs"',
            '"new graduate" "software" "hiring"',
            '"internship" "software engineer" "AI"',
            '"junior roles" "AI"',
        ],
        "role_anchor_group": None,
    },
    "ai_productivity": {
        "phrases": [
            '"developer productivity" "AI"',
            '"engineering productivity" "AI"',
            '"AI coding assistant"',
            '"GitHub Copilot" "productivity"',
            '"Cursor" "productivity"',
            '"Claude" "productivity"',
            '"Codex" "productivity"',
            '"code generation" "developer"',
            '"10x engineer" "AI"',
            '"AI pair programmer"',
            '"software velocity" "AI"',
        ],
        "role_anchor_group": "individual",
    },
    "corporate_restructuring": {
        "phrases": [
            '"AI" "reduce headcount"',
            '"AI" "fewer employees" "engineering"',
            '"AI" "right-size" "engineering"',
            '"AI" "efficiency" "headcount"',
            '"generative AI" "workforce"',
            '"AI" "restructuring" "software"',
            '"AI" "cost savings" "engineering"',
        ],
        "role_anchor_group": "collective",
    },
    "talent_demand": {
        "phrases": [
            '"engineer shortage"',
            '"developer shortage"',
            '"engineering talent" "demand"',
            '"hiring engineers"',
            '"demand for developers"',
            '"software engineer jobs" "growth"',
            '"AI engineer" "hiring"',
            '"AI fluent" "developer"',
        ],
        "role_anchor_group": "individual",
    },
    "role_creation": {
        "phrases": [
            '"AI engineer"',
            '"prompt engineer"',
            '"LLM engineer"',
            '"ML engineer" "hiring"',
            '"AI developer" "jobs"',
            '"new engineering roles"',
            '"AI infrastructure" "engineer"',
        ],
        "role_anchor_group": None,
    },
    "talent_pipeline": {
        "phrases": [
            '"CS enrollment"',
            '"computer science enrollment"',
            '"computer science degree" "enrollment"',
            '"coding bootcamp" "enrollment"',
            '"coding bootcamp" "closing"',
            '"software engineering degree" "enrollment"',
            '"STEM" "software" "enrollment"',
        ],
        "role_anchor_group": None,
    },
}
