version: 2

models:
  - name: int_headline_sentiment_topic
    description: "weekly headline sentiment intensity by topic"
    columns:
      - name: weekly_sentiment_score
        description: "The average sum of sentiment scores."
        tests:
          - not_null

      - name: source_name
        description: "Media source name."
        tests:
          - not_null

      - name: signal_topic
        description: "Signal topic."
        tests:
          - not_null

      - name: week_start_date
        description: "Truncated date to grain."
        tests:
          - not_null

  - name: int_headline_sentiment_total
    description: "weekly headline sentiment intensity total"
    columns:
      - name: week_start_date
        description: "Truncated date to grain."
        tests:
          - not_null

      - name: weekly_sentiment_score
        description: "The average sum of sentiment scores."
        tests:
          - not_null

  - name: int_company_daily_job_inventory
    description: "daily job inventory"
    columns:
      - name: company
        description: "Company being tracked."
        tests:
          - not_null

      - name: week_start_date
        description: "Aggregated week start date."
        tests:
          - not_null

      - name: total_visible_roles
        description: "Total job inventory across all search terms."
        tests:
          - not_null

      - name: search_terms_tracked
        description: "Total job inventory across all search terms."
        tests:
          - not_null
