version: 2

models:
  - name: mart_company_daily_job_inventory
    description: "daily job inventory"
    columns:
      - name: company
        description: "Company being tracked."
        tests:
          - not_null

      - name: day_ran
        description: "Date for when query ran."
        tests:
          - not_null

      - name: total_visible_roles
        description: "Total job inventory across all search terms."
        tests:
          - not_null

  - name: mart_company_daily_news_headlines
    description: "daily news headlines"
    columns:
      - name: publish_date
        description: "Date news story was posted."
        tests:
          - not_null

      - name: source_name
        description: "News company name."
        tests:
          - not_null

      - name: signal_topic
        description: "Batched topic querried."
        tests:
          - not_null

      - name: sentiment_compound_score
        description: "Sentiment compound score on title and description of story."
        tests:
          - not_null

      - name: sentiment_divergence
        description: "Divergence score between pos, neutral, and neg values."
